require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/story_notes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # StoryNote. As you add validations to StoryNote, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StoryNote.create! valid_attributes
      get story_notes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      story_note = StoryNote.create! valid_attributes
      get story_note_url(story_note)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_story_note_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      story_note = StoryNote.create! valid_attributes
      get edit_story_note_url(story_note)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StoryNote" do
        expect {
          post story_notes_url, params: { story_note: valid_attributes }
        }.to change(StoryNote, :count).by(1)
      end

      it "redirects to the created story_note" do
        post story_notes_url, params: { story_note: valid_attributes }
        expect(response).to redirect_to(story_note_url(StoryNote.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StoryNote" do
        expect {
          post story_notes_url, params: { story_note: invalid_attributes }
        }.to change(StoryNote, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post story_notes_url, params: { story_note: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested story_note" do
        story_note = StoryNote.create! valid_attributes
        patch story_note_url(story_note), params: { story_note: new_attributes }
        story_note.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the story_note" do
        story_note = StoryNote.create! valid_attributes
        patch story_note_url(story_note), params: { story_note: new_attributes }
        story_note.reload
        expect(response).to redirect_to(story_note_url(story_note))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        story_note = StoryNote.create! valid_attributes
        patch story_note_url(story_note), params: { story_note: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested story_note" do
      story_note = StoryNote.create! valid_attributes
      expect {
        delete story_note_url(story_note)
      }.to change(StoryNote, :count).by(-1)
    end

    it "redirects to the story_notes list" do
      story_note = StoryNote.create! valid_attributes
      delete story_note_url(story_note)
      expect(response).to redirect_to(story_notes_url)
    end
  end
end
